### ISSUE TITLE
Unable to get it work

### ISSUE THREAD

**Issue by washeree** [Erfaniaa/undervalued-crypto-finder#5]
Hello ;
First of all thank you for sharing this code with everyone. I was able to run it before and today i just want to try it again but i think something wrong while getting data from yahoo. I got these errors ;

C:\Users\xxx\Desktop\undervalued-crypto-finder-main>python main.py > output.txt
[*********************100%***********************]  3 of 3 completed

1 Failed download:
['BITCOIN']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[*********************100%***********************]  3 of 3 completed

1 Failed download:
['ETHEREUM']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[*********************100%***********************]  3 of 4 completed

2 Failed downloads:
[*********************100%***********************]  3 of 4 completed['USDT', 'TETHER']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[*********************100%***********************]  3 of 3 completed

1 Failed download:
['BNB']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 2024-04-02 -> 2024-10-18)')
[*********************100%***********************]  3 of 3 completed

1 Failed download:
['SOLANA']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
[*********************100%***********************]  3 of 3 completed
Traceback (most recent call last):
  File "C:\Users\xx\Desktop\undervalued-crypto-finder-main\main.py", line 135, in <module>
    main()
  File "C:\Users\xx\Desktop\undervalued-crypto-finder-main\main.py", line 107, in main
    undervalued_cryptos_list, pumped_or_dumped_cryptos_list = run(config.LOOK_BACK_DAYS, config.MAXIMUM_CRYPTOS_TO_CONSIDER)
  File "C:\Users\xx\Desktop\undervalued-crypto-finder-main\main.py", line 102, in run
    cryptos_list_with_info = get_cryptos_list_with_info(crypto_pair_names_list, start_time, end_time)
  File "C:\Users\xx\Desktop\undervalued-crypto-finder-main\main.py", line 72, in get_cryptos_list_with_info
    df = get_data_for_pair_name(pair_name, start_time, end_time)
  File "C:\Users\xx\Desktop\undervalued-crypto-finder-main\main.py", line 31, in get_data_for_pair_name
    df["Close to Open Percent"] = df.apply(lambda row: 100 * (row.Close - row.Open) / row.Open, axis=1)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4301, in __setitem__
    self._set_item_frame_value(key, value)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\frame.py", line 4459, in _set_item_frame_value
    raise ValueError(
ValueError: Cannot set a DataFrame with multiple columns to the single column Close to Open Percent

Looks like it cant get the time frame. Can you help or update the code when you have time please? 
Thank you

**Comment by washeree** [comment]
Ok, i made it work. I changed data path to "https://sg.finance.yahoo.com/crypto/?offset=0&count={maximum_cryptos_to_consider}". Also it works with screeners when i made custom screener.
